# Generated by Django 4.1.4 on 2022-12-27 21:33

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0002_game"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["when", "home_team__name", "away_team__name"]},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="game",
            name="when",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 27, 21, 33, 44, 606427, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="game",
            name="away_score",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="home_score",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(
                fields=("home_team", "away_team", "when"), name="unique_game"
            ),
        ),
    ]
